//
//  CommonStrings.swift
//  QatarMuseums
//
//  Created by Exalture on 17/08/18.
//  Copyright © 2018 Exalture. All rights reserved.
//

import Foundation
var ENG_LANGUAGE = "en"
var AR_LANGUAGE = "ar"
var ALREADY_REGISTERED = "You are already registered for another event at the selected time."
var UNREGISTER_CONFIRMATION_MESSAGE = "Are you sure you want to cancel the request to make your tour arrangements?"
var REGISTER = "Register"
var UNREGISTER = "UnRegister"
var YES = "Yes"
var NO = "No"
var LOCATION_ERROR = "Unfortunately we cannot open Map.";
var NO_END_TIME = "NO END TIME AVAILABLE"
var OK_MSG = "OK"
var PUBLICARTS_DETAIL = "PublicArtsDetailPage"
var HOME = "HomePage"
var EXHIBITION_DETAIL = "ExhibitionDetailPage"
var EVENT_VC = "EventPage"
var PROFILE_VC = "ProfilePage"
var EXHIBITION_LIST = "ExhibitionsPage"
var HERITAGE_LIST = "HeritageListPage"
var HERITAGE_DETAIL = "HeritageDetailPage"
var PUBLIC_ARTS_LIST = "PublicArtsPage"
var MUSEUM_COLLECTION = "MuseumCollectionsPage"
var MUSEUM_VC = "MuseumsPage"
var DINING_DETAIL = "DiningDetailPage"
var MIA_TOUR_GUIDE = "MiaTourGuidePage"
var MIA_TOURGUIDE_EXPLORE = "MiaTourGuideExplorePage"
var MIA_TOUR_DETAIL = "MiaTourDetailPage"
var NOTIFICATIONS_LIST = "NotificationsPage"
var TOUR_GUIDE_VC = "TourGuidePage"
var EDUCATION_VC = "EducationPage"
var DINING_LIST = "DiningPage"
var PARKS_VC = "ParksPage"
var FILTER_VC = "FilterPage"
var SETTINGS_VC = "SettingsPage"
var COLLECTION_DETAIL = "CollectionDetailPage"
var FLOORMAP_VC = "FloorMapPage"
var OBJECTDETAIL_VC = "ObjectDetailPage"
var ARTIFACT_NUMBER_VC = "ArtifactNumberPadPage"
var CULTUREPASS_VC = "CulturePassPage"
var MUSEUMS_ABOUT_VC = "MuseumAboutPage"
var PREVIEW_CONTENT_VC = "PreviewContentPage"
var PREVIEW_CONTAINER_VC = "PreviewContainerPage"
var CULTUREPASS_CARD_VC = "CulturePassCardPage"
var NMOQ_TOUR_LIST = "NMoQTourListPage"
var NMOQ_ACTIVITY_LIST = "NMoQActivityListPage"
var TRAVEL_ARRANGEMENT_VC = "TravelArrangementsPage"
var NMOQ_TOUR_SECOND_LIST = "NMoQTourPage"
var NMOQ_ACTIVITY_DETAIL = "NMoqPanelDiscussionDetailPage"
var NMOQ_TOUR_DETAIL = "NMoqTourDetailPage"
